apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: monitoring

resources:
  - podmonitor.yaml
  - otel-podmonitor.yaml

configMapGenerator:
  - name: grafana-dashboards-postgres
    files:
      - dashboards/pgbackrest.json
      - dashboards/pgbouncer_direct.json
      - dashboards/pod_details.json
      - dashboards/postgresql_details.json
      - dashboards/postgresql_overview.json
      - dashboards/postgresql_service_health.json
      - dashboards/query_statistics.json
      - dashboards/prometheus_alerts.json
    options:
      labels:
        grafana_dashboard: "1"

generatorOptions:
  disableNameSuffixHash: true
